// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_ACCOUNTDAYSTTL
#define LQTG_TYPE_ACCOUNTDAYSTTL

#include "telegramtypeobject.h"
#include <QtGlobal>

class LIBQTELEGRAMSHARED_EXPORT AccountDaysTTL : public TelegramTypeObject
{
public:
    enum AccountDaysTTLType {
        typeAccountDaysTTL = 0xb8d0afdf
    };

    AccountDaysTTL(AccountDaysTTLType classType = typeAccountDaysTTL, InboundPkt *in = 0);
    AccountDaysTTL(InboundPkt *in);
    virtual ~AccountDaysTTL();

    void setDays(qint32 days);
    qint32 days() const;

    void setClassType(AccountDaysTTLType classType);
    AccountDaysTTLType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const AccountDaysTTL &b);

private:
    qint32 m_days;
    AccountDaysTTLType m_classType;
};

#endif // LQTG_TYPE_ACCOUNTDAYSTTL
