// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_AUTHCHECKEDPHONE
#define LQTG_TYPE_AUTHCHECKEDPHONE

#include "telegramtypeobject.h"

class LIBQTELEGRAMSHARED_EXPORT AuthCheckedPhone : public TelegramTypeObject
{
public:
    enum AuthCheckedPhoneType {
        typeAuthCheckedPhone = 0x811ea28e
    };

    AuthCheckedPhone(AuthCheckedPhoneType classType = typeAuthCheckedPhone, InboundPkt *in = 0);
    AuthCheckedPhone(InboundPkt *in);
    virtual ~AuthCheckedPhone();

    void setPhoneRegistered(bool phoneRegistered);
    bool phoneRegistered() const;

    void setClassType(AuthCheckedPhoneType classType);
    AuthCheckedPhoneType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const AuthCheckedPhone &b);

private:
    bool m_phoneRegistered;
    AuthCheckedPhoneType m_classType;
};

#endif // LQTG_TYPE_AUTHCHECKEDPHONE
