// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_CHATINVITE
#define LQTG_TYPE_CHATINVITE

#include "telegramtypeobject.h"
#include "chat.h"
#include <QString>

class LIBQTELEGRAMSHARED_EXPORT ChatInvite : public TelegramTypeObject
{
public:
    enum ChatInviteType {
        typeChatInviteAlready = 0x5a686d7c,
        typeChatInvite = 0xce917dcd
    };

    ChatInvite(ChatInviteType classType = typeChatInviteAlready, InboundPkt *in = 0);
    ChatInvite(InboundPkt *in);
    virtual ~ChatInvite();

    void setChat(const Chat &chat);
    Chat chat() const;

    void setTitle(const QString &title);
    QString title() const;

    void setClassType(ChatInviteType classType);
    ChatInviteType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const ChatInvite &b);

private:
    Chat m_chat;
    QString m_title;
    ChatInviteType m_classType;
};

#endif // LQTG_TYPE_CHATINVITE
