// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_HELPINVITETEXT
#define LQTG_TYPE_HELPINVITETEXT

#include "telegramtypeobject.h"
#include <QString>

class LIBQTELEGRAMSHARED_EXPORT HelpInviteText : public TelegramTypeObject
{
public:
    enum HelpInviteTextType {
        typeHelpInviteText = 0x18cb9f78
    };

    HelpInviteText(HelpInviteTextType classType = typeHelpInviteText, InboundPkt *in = 0);
    HelpInviteText(InboundPkt *in);
    virtual ~HelpInviteText();

    void setMessage(const QString &message);
    QString message() const;

    void setClassType(HelpInviteTextType classType);
    HelpInviteTextType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const HelpInviteText &b);

private:
    QString m_message;
    HelpInviteTextType m_classType;
};

#endif // LQTG_TYPE_HELPINVITETEXT
