// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_INPUTPRIVACYKEY
#define LQTG_TYPE_INPUTPRIVACYKEY

#include "telegramtypeobject.h"

class LIBQTELEGRAMSHARED_EXPORT InputPrivacyKey : public TelegramTypeObject
{
public:
    enum InputPrivacyKeyType {
        typeInputPrivacyKeyStatusTimestamp = 0x4f96cb18
    };

    InputPrivacyKey(InputPrivacyKeyType classType = typeInputPrivacyKeyStatusTimestamp, InboundPkt *in = 0);
    InputPrivacyKey(InboundPkt *in);
    virtual ~InputPrivacyKey();

    void setClassType(InputPrivacyKeyType classType);
    InputPrivacyKeyType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const InputPrivacyKey &b);

private:
    InputPrivacyKeyType m_classType;
};

#endif // LQTG_TYPE_INPUTPRIVACYKEY
