// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "inputgeopoint.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

InputGeoPoint::InputGeoPoint(InputGeoPointType classType, InboundPkt *in) :
    m_lat(0),
    m_longValue(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

InputGeoPoint::InputGeoPoint(InboundPkt *in) :
    m_lat(0),
    m_longValue(0),
    m_classType(typeInputGeoPointEmpty)
{
    fetch(in);
}

InputGeoPoint::~InputGeoPoint() {
}

void InputGeoPoint::setLat(qreal lat) {
    m_lat = lat;
}

qreal InputGeoPoint::lat() const {
    return m_lat;
}

void InputGeoPoint::setLongValue(qreal longValue) {
    m_longValue = longValue;
}

qreal InputGeoPoint::longValue() const {
    return m_longValue;
}

bool InputGeoPoint::operator ==(const InputGeoPoint &b) {
    return m_lat == b.m_lat &&
           m_longValue == b.m_longValue;
}

void InputGeoPoint::setClassType(InputGeoPoint::InputGeoPointType classType) {
    m_classType = classType;
}

InputGeoPoint::InputGeoPointType InputGeoPoint::classType() const {
    return m_classType;
}

bool InputGeoPoint::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeInputGeoPointEmpty: {
        m_classType = static_cast<InputGeoPointType>(x);
        return true;
    }
        break;
    
    case typeInputGeoPoint: {
        m_lat = in->fetchDouble();
        m_longValue = in->fetchDouble();
        m_classType = static_cast<InputGeoPointType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool InputGeoPoint::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeInputGeoPointEmpty: {
        return true;
    }
        break;
    
    case typeInputGeoPoint: {
        out->appendDouble(m_lat);
        out->appendDouble(m_longValue);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

