// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_MESSAGESMESSAGE
#define LQTG_TYPE_MESSAGESMESSAGE

#include "telegramtypeobject.h"

class LIBQTELEGRAMSHARED_EXPORT MessagesMessage : public TelegramTypeObject
{
public:
    enum MessagesMessageType {
        typeMessagesMessageEmpty = 0x3f4e0648
    };

    MessagesMessage(MessagesMessageType classType = typeMessagesMessageEmpty, InboundPkt *in = 0);
    MessagesMessage(InboundPkt *in);
    virtual ~MessagesMessage();

    void setClassType(MessagesMessageType classType);
    MessagesMessageType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const MessagesMessage &b);

private:
    MessagesMessageType m_classType;
};

#endif // LQTG_TYPE_MESSAGESMESSAGE
