// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_MESSAGESCHATS
#define LQTG_TYPE_MESSAGESCHATS

#include "telegramtypeobject.h"
#include <QList>
#include "chat.h"

class LIBQTELEGRAMSHARED_EXPORT MessagesChats : public TelegramTypeObject
{
public:
    enum MessagesChatsType {
        typeMessagesChats = 0x64ff9fd5
    };

    MessagesChats(MessagesChatsType classType = typeMessagesChats, InboundPkt *in = 0);
    MessagesChats(InboundPkt *in);
    virtual ~MessagesChats();

    void setChats(const QList<Chat> &chats);
    QList<Chat> chats() const;

    void setClassType(MessagesChatsType classType);
    MessagesChatsType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const MessagesChats &b);

private:
    QList<Chat> m_chats;
    MessagesChatsType m_classType;
};

#endif // LQTG_TYPE_MESSAGESCHATS
