// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_MESSAGESCHATFULL
#define LQTG_TYPE_MESSAGESCHATFULL

#include "telegramtypeobject.h"
#include <QList>
#include "chat.h"
#include "chatfull.h"
#include "user.h"

class LIBQTELEGRAMSHARED_EXPORT MessagesChatFull : public TelegramTypeObject
{
public:
    enum MessagesChatFullType {
        typeMessagesChatFull = 0xe5d7d19c
    };

    MessagesChatFull(MessagesChatFullType classType = typeMessagesChatFull, InboundPkt *in = 0);
    MessagesChatFull(InboundPkt *in);
    virtual ~MessagesChatFull();

    void setChats(const QList<Chat> &chats);
    QList<Chat> chats() const;

    void setFullChat(const ChatFull &fullChat);
    ChatFull fullChat() const;

    void setUsers(const QList<User> &users);
    QList<User> users() const;

    void setClassType(MessagesChatFullType classType);
    MessagesChatFullType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const MessagesChatFull &b);

private:
    QList<Chat> m_chats;
    ChatFull m_fullChat;
    QList<User> m_users;
    MessagesChatFullType m_classType;
};

#endif // LQTG_TYPE_MESSAGESCHATFULL
