// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_PEERNOTIFYEVENTS
#define LQTG_TYPE_PEERNOTIFYEVENTS

#include "telegramtypeobject.h"

class LIBQTELEGRAMSHARED_EXPORT PeerNotifyEvents : public TelegramTypeObject
{
public:
    enum PeerNotifyEventsType {
        typePeerNotifyEventsEmpty = 0xadd53cb3,
        typePeerNotifyEventsAll = 0x6d1ded88
    };

    PeerNotifyEvents(PeerNotifyEventsType classType = typePeerNotifyEventsEmpty, InboundPkt *in = 0);
    PeerNotifyEvents(InboundPkt *in);
    virtual ~PeerNotifyEvents();

    void setClassType(PeerNotifyEventsType classType);
    PeerNotifyEventsType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const PeerNotifyEvents &b);

private:
    PeerNotifyEventsType m_classType;
};

#endif // LQTG_TYPE_PEERNOTIFYEVENTS
