// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_PRIVACYKEY
#define LQTG_TYPE_PRIVACYKEY

#include "telegramtypeobject.h"

class LIBQTELEGRAMSHARED_EXPORT PrivacyKey : public TelegramTypeObject
{
public:
    enum PrivacyKeyType {
        typePrivacyKeyStatusTimestamp = 0xbc2eab30
    };

    PrivacyKey(PrivacyKeyType classType = typePrivacyKeyStatusTimestamp, InboundPkt *in = 0);
    PrivacyKey(InboundPkt *in);
    virtual ~PrivacyKey();

    void setClassType(PrivacyKeyType classType);
    PrivacyKeyType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const PrivacyKey &b);

private:
    PrivacyKeyType m_classType;
};

#endif // LQTG_TYPE_PRIVACYKEY
