// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "help.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

using namespace Tg;

Functions::Help::Help() {
}

Functions::Help::~Help() {
}

bool Functions::Help::getConfig(OutboundPkt *out) {
    out->appendInt(fncHelpGetConfig);
    return true;
}

Config Functions::Help::getConfigResult(InboundPkt *in) {
    Config result;
    if(!result.fetch(in)) return result;
    return result;
}

bool Functions::Help::getNearestDc(OutboundPkt *out) {
    out->appendInt(fncHelpGetNearestDc);
    return true;
}

NearestDc Functions::Help::getNearestDcResult(InboundPkt *in) {
    NearestDc result;
    if(!result.fetch(in)) return result;
    return result;
}

bool Functions::Help::getAppUpdate(OutboundPkt *out, const QString &deviceModel, const QString &systemVersion, const QString &appVersion, const QString &langCode) {
    out->appendInt(fncHelpGetAppUpdate);
    out->appendQString(deviceModel);
    out->appendQString(systemVersion);
    out->appendQString(appVersion);
    out->appendQString(langCode);
    return true;
}

HelpAppUpdate Functions::Help::getAppUpdateResult(InboundPkt *in) {
    HelpAppUpdate result;
    if(!result.fetch(in)) return result;
    return result;
}

bool Functions::Help::saveAppLog(OutboundPkt *out, const QList<InputAppEvent> &events) {
    out->appendInt(fncHelpSaveAppLog);
    out->appendInt(CoreTypes::typeVector);
    out->appendInt(events.count());
    for (qint32 i = 0; i < events.count(); i++) {
        if(!events[i].push(out)) return false;
    }
    return true;
}

bool Functions::Help::saveAppLogResult(InboundPkt *in) {
    bool result;
    result = in->fetchBool();
    return result;
}

bool Functions::Help::getInviteText(OutboundPkt *out, const QString &langCode) {
    out->appendInt(fncHelpGetInviteText);
    out->appendQString(langCode);
    return true;
}

HelpInviteText Functions::Help::getInviteTextResult(InboundPkt *in) {
    HelpInviteText result;
    if(!result.fetch(in)) return result;
    return result;
}

bool Functions::Help::getSupport(OutboundPkt *out) {
    out->appendInt(fncHelpGetSupport);
    return true;
}

HelpSupport Functions::Help::getSupportResult(InboundPkt *in) {
    HelpSupport result;
    if(!result.fetch(in)) return result;
    return result;
}

