// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "updates.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

using namespace Tg;

Functions::Updates::Updates() {
}

Functions::Updates::~Updates() {
}

bool Functions::Updates::getState(OutboundPkt *out) {
    out->appendInt(fncUpdatesGetState);
    return true;
}

UpdatesState Functions::Updates::getStateResult(InboundPkt *in) {
    UpdatesState result;
    if(!result.fetch(in)) return result;
    return result;
}

bool Functions::Updates::getDifference(OutboundPkt *out, qint32 pts, qint32 date, qint32 qts) {
    out->appendInt(fncUpdatesGetDifference);
    out->appendInt(pts);
    out->appendInt(date);
    out->appendInt(qts);
    return true;
}

UpdatesDifference Functions::Updates::getDifferenceResult(InboundPkt *in) {
    UpdatesDifference result;
    if(!result.fetch(in)) return result;
    return result;
}

