// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "users.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

using namespace Tg;

Functions::Users::Users() {
}

Functions::Users::~Users() {
}

bool Functions::Users::getUsers(OutboundPkt *out, const QList<InputUser> &id) {
    out->appendInt(fncUsersGetUsers);
    out->appendInt(CoreTypes::typeVector);
    out->appendInt(id.count());
    for (qint32 i = 0; i < id.count(); i++) {
        if(!id[i].push(out)) return false;
    }
    return true;
}

QList<User> Functions::Users::getUsersResult(InboundPkt *in) {
    QList<User> result;
    if(in->fetchInt() != (qint32)CoreTypes::typeVector) return result;
    qint32 result_length = in->fetchInt();
    result.clear();
    for (qint32 i = 0; i < result_length; i++) {
        User type;
        if(!type.fetch(in)) return result;
        result.append(type);
    }
    return result;
}

bool Functions::Users::getFullUser(OutboundPkt *out, const InputUser &id) {
    out->appendInt(fncUsersGetFullUser);
    if(!id.push(out)) return false;
    return true;
}

UserFull Functions::Users::getFullUserResult(InboundPkt *in) {
    UserFull result;
    if(!result.fetch(in)) return result;
    return result;
}

