// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef CORETYPES_H
#define CORETYPES_H

class CoreTypes 
{
public:
    enum Types {
        typeBoolFalse = 0xbc799737,
        typeBoolTrue = 0x997275b5,
        typeError = 0xc4b9f9bb,
        typeInitConnection = 0x69796de9,
        typeInvokeAfterMsg = 0xcb9f372d,
        typeInvokeAfterMsgs = 0x3dc4b4f0,
        typeInvokeWithLayer = 0xda9b0d0d,
        typeInvokeWithoutUpdates = 0xbf9459b7,
        typeNull = 0x56730bcc,
        typeVector = 0x1cb5c415,
        typeLayerVersion = 29
    };
};

#endif //CORETYPES_H
