# This file generated by libqtelegram-code-generator.
# You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN


include(functions/functions.pri)
include(types/types.pri)

HEADERS += \
    $$PWD/coretypes.h

