// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef TELEGRAMFUNCTIONOBJECT_H
#define TELEGRAMFUNCTIONOBJECT_H

#include <QtGlobal>
#include "libqtelegram_global.h"

class InboundPkt;
class OutboundPkt;
class LIBQTELEGRAMSHARED_EXPORT TelegramFunctionObject
{
public:
};

#endif // TELEGRAMFUNCTIONOBJECT_H
