// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "telegramcustomtypeobject.h"

TelegramCustomTypeObject::TelegramCustomTypeObject() :
    mNull(false)
{
}

TelegramCustomTypeObject::TelegramCustomTypeObject(const Null&) :
    mNull(true)
{
}

TelegramCustomTypeObject::~TelegramCustomTypeObject()
{
}

