// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef TELEGRAMTYPEQOBJECT_H
#define TELEGRAMTYPEQOBJECT_H

#include "libqtelegram_global.h"
#include <QObject>

class LIBQTELEGRAMSHARED_EXPORT TelegramTypeQObject: public QObject
{
    Q_OBJECT
public:
    TelegramTypeQObject(QObject *parent = 0);
    virtual ~TelegramTypeQObject();

    static qint64 constructedCount() {
        return mConstructedCount;
    }

private:
    static qint64 mConstructedCount;
};

#endif // TELEGRAMTYPEQOBJECT_H
