// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "telegramapi.h"
#include "telegram/types/types.h"
#include "telegram/functions/functions.h"
#include "telegram/coretypes.h"

#include "util/tlvalues.h"
#include "core/dcprovider.h"
#include "secret/encrypter.h"

Q_LOGGING_CATEGORY(TG_CORE_API, "tg.core.api")

#define DEBUG_FUNCTION \
    qCDebug(TG_CORE_API) << __LINE__ << __FUNCTION__;

#define CHECK_SESSION(SESSION) \
    if(!SESSION) \
        return 0;

#define INIT_MAIN_CONNECTION(SESSION)

using namespace Tg;

TelegramApi::TelegramApi(Session *session, Settings *settings, CryptoUtils *crypto, QObject *parent) :
    AbstractApi(session, settings, crypto, parent),
    mSettings(settings),
    mCrypto(crypto)
{
/*! === constructor === !*/
}

TelegramApi::~TelegramApi() {
}

/*! === methods === !*/
void TelegramApi::onError(Query *q, qint32 errorCode, const QString &errorText, const QVariant &attachedData, bool &accepted) {
    Q_EMIT error(q->msgId(), errorCode, errorText, q->name(), attachedData, accepted);
}
