// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "telegramtypeqobject.h"

qint64 TelegramTypeQObject::mConstructedCount = 0;

TelegramTypeQObject::TelegramTypeQObject(QObject *parent) :
    QObject(parent)
{
    mConstructedCount++;
}

TelegramTypeQObject::~TelegramTypeQObject()
{
    mConstructedCount--;
}

